---
title: "QuoteFinder Twitter bot"
author: "Giorgio Comai (OBCT/CCI)"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
if (!require("pacman")) install.packages("pacman",  repos = "https://cloud.r-project.org") # for taking care of package installation/loading
pacman::p_load("tidyverse")
pacman::p_load("tidytext")
pacman::p_load("ROAuth")
pacman::p_load("rtweet")
pacman::p_load("stringr")
pacman::p_load("reshape2")
pacman::p_load("wordcloud")
# pacman::p_load("devtools")
# devtools::install_github("mkearney/rtweet")
# library("rtweet")

library(wordcloud2)
pacman::p_load(RColorBrewer)

pacman::p_load(webshot)
pacman::p_load(htmlwidgets)

bluesFunc <- colorRampPalette(colors = c("#4292C6", "#08306B"))
blues <- bluesFunc(5)

dir.create(path = "img",showWarnings = FALSE)

twitter_token <- readRDS(file = "twitter_token.rds")
```

```{r load data}
dataFolder <- "/srv/shiny-server/QuoteFinderApp/data"
dataset <- readRDS(file = file.path(dataFolder, "dataset.rds")) %>% 
  filter(date>Sys.Date()-31)
#topHashtag <- readRDS(file = file.path(dataFolder, "hashtags.rds"))

lang <- data_frame(lang = unlist(dataset$lang)) %>%
  tidyr::drop_na() %>%
  count(lang, sort = TRUE) %>% select(lang)
langL <- as.list(lang$lang)

hashtags <- vector("list", length = length(langL))
hashtags <- setNames(object = hashtags, nm = unlist(langL))
for (i in seq_along(langL)) {
  tempL <- data_frame(hashtags = dataset %>%
               filter(lang==langL[[i]]) %>%
               select(hashtags) %>% 
               unlist()) %>% 
    tidyr::drop_na()  %>%
    count(hashtags, sort = TRUE) %>% # make hashtags in order of most frequent, by language
    mutate(hashtagsLower = tolower(hashtags)) %>% # ignore case, but keep the case of the most frequently found case combination
    group_by(hashtagsLower) %>%
    add_tally(wt = n) %>%
    distinct(hashtagsLower, .keep_all = TRUE) %>%
    arrange(desc(nn)) %>% 
    ungroup() %>%
    mutate(hashtags = paste0(hashtags, " (", nn, ")")) %>% 
    select(hashtags) %>% 
    pull(hashtags) %>%
    as.list()
  if (length(tempL) == 0) {
     names(tempL) <- NULL
  } else {
    names(tempL) <- paste0("#", unlist(tempL))
  }
  hashtags[[i]] <- tempL
}

```

Pick a hashtag randomly among top 10

```{r no sentiment hashtag}

randomTopHashtag <- unlist(sample(head(hashtags$en, 10), 1))

NrOfTweets <- str_extract(string = randomTopHashtag, pattern = "([[:digit:]]+)")
hashtag <- str_extract(string = randomTopHashtag, pattern = "([[:alnum:]]+)")

dataset <- dataset %>% 
  filter(lang=="en") %>% 
  filter(purrr::map_lgl(.x = hashtags, .f = function (x) is.element(el = as.character(hashtag), set = x))) %>%
    select(clean_text) %>% 
  unnest_tokens(input = clean_text, output = word) %>% 
  # remove stopwords, if list for the relevant language is available, otherwise do nothing
  when(is.element(el = "en", set = stopwords::stopwords_getlanguages(source = "stopwords-iso")) ~
         anti_join(., data_frame(word = stopwords::stopwords(language = "en", source = "stopwords-iso")), by = "word"),
       ~ .) %>% 
count(word, sort = TRUE)  

# customise output color, gradients of blue by frequency
colour <- dataset %>% 
  mutate(colour = case_when(
    n <= quantile(n)[1] ~ blues[1],
    n > quantile(n)[1]& n<=quantile(n)[2] ~ blues[2],
    n > quantile(n)[2]& n<=quantile(n)[3] ~ blues[3],
    n > quantile(n)[3]& n<=quantile(n)[4] ~ blues[4],
    n > quantile(n)[4]& n<=quantile(n)[5] ~ blues[4]
  )) %>% pull(colour)

sizeVar <- as.numeric(quantile(dataset$n)[5]/quantile(dataset$n)[1]/nrow(dataset)*44)
graph <- dataset %>%
  wordcloud2(size = sizeVar, color = colour)

graph <- dataset %>% wordcloud2(color = colour, size = sizeVar)

filename <- file.path("img", paste(Sys.time(), "wordcloud2 1month hashtag", hashtag, "EN.png", sep = "-"))

saveWidget(graph,"tmp.html",selfcontained = FALSE)
webshot("tmp.html", filename, delay = 10, vwidth = 2048, vheight = 1512)

randomTopHashtag

```

```{r}
# Post tweet
post_tweet(status = paste0("In the last month, MEPs posted ", NrOfTweets, " tweets in English with the hashtag #", hashtag, ". This is what it was all about. Explore the tweets also in other languages at https://www.europeandatajournalism.eu/Tools-for-journalists/Quote-Finder/"), media = filename, token = twitter_token)
```